import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "src", "main", "resources", "seed", "startup-graph.json")
OUT = os.path.join(ROOT, "scripts", "seed.cypher")


def q(value):
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def main():
    with open(DATA, encoding="utf-8") as fh:
        data = json.load(fh)

    lines = []
    lines.append("// VentureGraph seed data — idempotent, safe to re-run.")
    lines.append("// Generated by scripts/generate_seed_cypher.py from src/main/resources/seed/startup-graph.json")
    lines.append("")

    for name in data["industries"]:
        lines.append(f"MERGE (n:Industry {{name: {q(name)}}});")
    lines.append("")

    for name in data["universities"]:
        lines.append(f"MERGE (n:University {{name: {q(name)}}});")
    lines.append("")

    for c in data["companies"]:
        props = ", ".join(f"c.{k} = {q(v)}" for k, v in c.items() if k != "name")
        lines.append(f"MERGE (c:Company {{name: {q(c['name'])}}}) SET {props};")
    lines.append("")

    for p in data["people"]:
        props = ", ".join(f"p.{k} = {q(v)}" for k, v in p.items() if k != "name")
        lines.append(f"MERGE (p:Person {{name: {q(p['name'])}}}) SET {props};")
    lines.append("")

    for i in data["investors"]:
        props = ", ".join(f"i.{k} = {q(v)}" for k, v in i.items() if k != "name")
        lines.append(f"MERGE (i:Investor {{name: {q(i['name'])}}}) SET {props};")
    lines.append("")

    rel_map = {
        "founded": "FOUNDED",
        "workedAt": "WORKED_AT",
        "graduatedFrom": "GRADUATED_FROM",
        "investedIn": "INVESTED_IN",
        "operatesIn": "OPERATES_IN",
        "partnersWith": "PARTNERS_WITH",
        "knows": "KNOWS",
    }
    for key, rel_type in rel_map.items():
        for row in data[key]:
            props = ", ".join(f"r.{k} = {q(v)}" for k, v in row.items() if k not in ("from", "to"))
            lines.append(
                f"MATCH (a {{name: {q(row['from'])}}}) MATCH (b {{name: {q(row['to'])}}}) "
                f"MERGE (a)-[r:{rel_type}]->(b) SET {props};"
            )
        lines.append("")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"Wrote {len(lines)} statements to {OUT}")


if __name__ == "__main__":
    sys.exit(main())
